### ISSUE TITLE
wrong file date on leap year/day

### ISSUE THREAD

**Issue by khambrecht** [ogham/exa#101]
eax shows wrong file date on leap year/day (e.g. 29th feb 2016):

ls output:
$ ls -la file_created_on_29th_Feb_2016.txt 
-rw-r--r-- 1 khambrecht users 0 29. Feb 11:13 file_created_on_29th_Feb_2016.txt

exa output on same file:
$ exa -la file_created_on_29th_Feb_2016.txt 
.rw-r--r-- 0 khambrecht  1 Mar 11:13 file_created_on_29th_Feb_2016.txt

**Comment by ogham** [comment]
Oh man. I hate date-time.

**Comment by ogham** [comment]
This should be fixed when exa updates to the version of rust-datetime that has the fix.

**Comment by khambrecht** [comment]
any chance to get this in place soon? Next Feb 29th is comming closer and closer ... ;-)

**Comment by JoshMock** [comment]
Still happening as of today, leap day 2020. 🙂 

`ls` works:

```bash
$ ls -la resources/public
total 448
drwxr-xr-x  6 joshmock  staff     192 Feb 20 13:51 .
drwxr-xr-x  4 joshmock  staff     128 Feb 29 09:41 ..
-rw-r--r--  1 joshmock  staff    4286 Feb 29 09:54 favicon.ico
-rw-r--r--  1 joshmock  staff    4145 Feb 29 09:54 index.html
-rw-r--r--  1 joshmock  staff   80350 Feb 29 09:54 main.css
-rw-r--r--  1 joshmock  staff  130601 Feb 29 09:54 main.js
```

`exa` is wrong:

```bash
$ exa --long --header --all resources/public
Permissions Size User     Date Modified Name
.rw-r--r--  4.3k joshmock  1 Mar  9:54  favicon.ico
.rw-r--r--  4.1k joshmock  1 Mar  9:54  index.html
.rw-r--r--   80k joshmock  1 Mar  9:54  main.css
.rw-r--r--  130k joshmock  1 Mar  9:54  main.js
```

**Comment by ariasuni** [comment]
This was fixed by updating the `datetime` crate in da1ac5139bb0b9c36336f010bcc5346cde6bae8d, there just hasn’t been a new release made since then.
