### ISSUE TITLE
Compiling on OS X Yosemite

### ISSUE THREAD

**Issue by lovek323** [ogham/exa#60]
I'm getting the following errors when I try to compile on OS X Yosemite (`rustc 1.1.0-nightly (da623844a 2015-04-25) (built 2015-04-25)`):

```
cargo build --release --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading locale v0.1.7
 Downloading natord v1.0.8
 Downloading regex_macros v0.1.15
 Downloading bitflags v0.1.1
 Downloading time v0.1.25
 Downloading libc v0.1.6
 Downloading libssh2-sys v0.1.18
 Downloading gcc v0.3.4
 Downloading users v0.3.2
 Downloading pkg-config v0.3.3
 Downloading regex v0.1.27
 Downloading getopts v0.2.9
 Downloading pad v0.1.3
 Downloading num_cpus v0.1.0
 Downloading rustc-serialize v0.3.12
 Downloading matches v0.1.2
 Downloading log v0.3.1
 Downloading openssl-sys v0.6.0
   Compiling regex v0.1.27
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.27/src/lib.rs --crate-name regex --crate-type lib -C opt-level=3 --cfg feature="pattern" -C metadata=792c67aed9f650b7 -C extra-filename=-792c67aed9f650b7 --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
   Compiling matches v0.1.2
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/matches-0.1.2/lib.rs --crate-name matches --crate-type lib -C opt-level=3 -C metadata=68db25b520030534 -C extra-filename=-68db25b520030534 --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
   Compiling rustc-serialize v0.3.12
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.12/src/lib.rs --crate-name rustc_serialize --crate-type lib -C opt-level=3 -C metadata=70d93d5334da1e4e -C extra-filename=-70d93d5334da1e4e --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
   Compiling pad v0.1.3
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/pad-0.1.3/src/lib.rs --crate-name pad --crate-type lib -C opt-level=3 -C metadata=548f040d9866039b -C extra-filename=-548f040d9866039b --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
   Compiling libc v0.1.6
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.6/rust/src/liblibc/lib.rs --crate-name libc --crate-type lib -C opt-level=3 --cfg feature="default" --cfg feature="cargo-build" -C metadata=9b7976990ae0dbd4 -C extra-filename=-9b7976990ae0dbd4 --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
   Compiling natord v1.0.8
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/natord-1.0.8/lib.rs --crate-name natord --crate-type lib -C opt-level=3 -C metadata=03a0e75cb3de3267 -C extra-filename=-03a0e75cb3de3267 --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
   Compiling bitflags v0.1.1
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-0.1.1/src/lib.rs --crate-name bitflags --crate-type lib -C opt-level=3 -C metadata=518ea12e21428edd -C extra-filename=-518ea12e21428edd --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
   Compiling number_prefix v0.2.3
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/number_prefix-0.2.3/src/lib.rs --crate-name number_prefix --crate-type lib -C opt-level=3 -C metadata=48981b1280686d7e -C extra-filename=-48981b1280686d7e --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/number_prefix-0.2.3/src/lib.rs:92:5: 92:20 error: unresolved import `std::num::Float`. There is no `Float` in `std::num`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/number_prefix-0.2.3/src/lib.rs:92 use std::num::Float;
                                                                                                          ^~~~~~~~~~~~~~~
error: aborting due to previous error
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/natord-1.0.8/lib.rs:88:34: 97:26 note: shadowed label `'digits` declared here
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/natord-1.0.8/lib.rs:88                         'digits: loop {
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/natord-1.0.8/lib.rs:89                             read_left!();
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/natord-1.0.8/lib.rs:90                             read_right!();
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/natord-1.0.8/lib.rs:91                             match (ll, rr) {
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/natord-1.0.8/lib.rs:92                                 (Some(ll_), Some(rr_)) => return_unless_equal!(ll_.cmp(&rr_)),
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/natord-1.0.8/lib.rs:93                                 (Some(_), None) => return Greater,
                                                                                           ...
   Compiling gcc v0.3.4
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.4/src/lib.rs --crate-name gcc --crate-type lib -C opt-level=3 -C metadata=dcfc3982b26642f7 -C extra-filename=-dcfc3982b26642f7 --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.12/src/json.rs:244:16: 244:21 error: unresolved import `std::num::Float`. There is no `Float` in `std::num`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.12/src/json.rs:244 use std::num::{Float, Int};
                                                                                                                          ^~~~~
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.12/src/json.rs:244:23: 244:26 error: unresolved import `std::num::Int`. There is no `Int` in `std::num`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.12/src/json.rs:244 use std::num::{Float, Int};
                                                                                                                                 ^~~
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.12/src/serialize.rs:18:16: 18:23 error: unresolved import `std::ffi::AsOsStr`. There is no `AsOsStr` in `std::ffi`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.12/src/serialize.rs:18 use std::ffi::{AsOsStr, OsString};
                                                                                                                              ^~~~~~~
error: aborting due to 3 previous errors
   Compiling ansi_term v0.5.1
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.5.1/src/ansi_term.rs --crate-name ansi_term --crate-type lib -C opt-level=3 -C metadata=2362f75d20657324 -C extra-filename=-2362f75d20657324 --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/pad-0.1.3/src/lib.rs:5:4: 5:12 error: stability attributes may not be used outside of the standard library
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/pad-0.1.3/src/lib.rs:5 #![unstable]
                                                                                              ^~~~~~~~
error: aborting due to previous error
   Compiling pkg-config v0.3.3
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.3/src/lib.rs --crate-name pkg_config --crate-type lib -C opt-level=3 -C metadata=c0e9294bfeefddd9 -C extra-filename=-c0e9294bfeefddd9 --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
   Compiling locale v0.1.7
     Running `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/locale-0.1.7/src/lib.rs --crate-name locale --crate-type lib -C opt-level=3 -C metadata=d77ca3fc1f74437e -C extra-filename=-d77ca3fc1f74437e --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings`
Build failed, waiting for other jobs to finish...
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/locale-0.1.7/src/lib.rs:22:16: 22:19 error: unresolved import `std::num::Int`. There is no `Int` in `std::num`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/locale-0.1.7/src/lib.rs:22 use std::num::{Int, Float};
                                                                                                              ^~~
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/locale-0.1.7/src/lib.rs:22:21: 22:26 error: unresolved import `std::num::Float`. There is no `Float` in `std::num`
/Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/locale-0.1.7/src/lib.rs:22 use std::num::{Int, Float};
                                                                                                                   ^~~~~
error: aborting due to 2 previous errors
Could not compile `number_prefix`.

Caused by:
  Process didn't exit successfully: `rustc /Users/jason.oconal/.cargo/registry/src/github.com-1ecc6299db9ec823/number_prefix-0.2.3/src/lib.rs --crate-name number_prefix --crate-type lib -C opt-level=3 -C metadata=48981b1280686d7e -C extra-filename=-48981b1280686d7e --out-dir /Users/jason.oconal/code/exa/target/release/deps --emit=dep-info,link -L dependency=/Users/jason.oconal/code/exa/target/release/deps -L dependency=/Users/jason.oconal/code/exa/target/release/deps -Awarnings` (exit code: 101)
make: *** [target/release/exa] Error 101
```

**Comment by ogham** [comment]
Try running a `cargo update` - some dependencies hadn't been updated to use the latest nightly (`std::num` changes), but now they are. I just fixed my datetime crate.

Unfortunately, if you get it to compile, you'll find that a bunch of data is missing. This is because the old_io implementation isn't around anymore, and the new one doesn't have all the Unix extensions yet (see https://github.com/rust-lang/rust/pull/24711). There's a `new_fs` branch if you want to get something compilable, though.

**Comment by davidcelis** [comment]
After a `cargo update`, building still fails; though it fails on compiling `users` now:

```
cargo build --release
 Downloading getopts v0.2.10
 Downloading num v0.1.24
 Downloading locale v0.1.8
 Downloading number_prefix v0.2.4
 Downloading regex_macros v0.1.17
 Downloading unicode-width v0.1.1
 Downloading rustc-serialize v0.3.14
 Downloading openssl-sys v0.6.1
 Downloading rand v0.3.8
 Downloading pad v0.1.4
 Downloading libz-sys v0.1.3
 Downloading url v0.2.31
 Downloading regex v0.1.30
 Downloading datetime v0.1.7
 Downloading num_cpus v0.2.3
   Compiling unicode-width v0.1.1
   Compiling rustc-serialize v0.3.14
   Compiling regex v0.1.30
   Compiling openssl-sys v0.6.1
   Compiling libz-sys v0.1.3
   Compiling libgit2-sys v0.2.12 (https://github.com/alexcrichton/git2-rs.git#c9eea60c)
   Compiling libssh2-sys v0.1.18
   Compiling num_cpus v0.2.3
   Compiling log v0.3.1
   Compiling users v0.3.2
   Compiling rand v0.3.8
/Users/david/.cargo/registry/src/github.com-1ecc6299db9ec823/users-0.3.2/src/lib.rs:5:1: 5:47 error: unstable feature
/Users/david/.cargo/registry/src/github.com-1ecc6299db9ec823/users-0.3.2/src/lib.rs:5 #![feature(collections, core, libc, std_misc)]
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
   Compiling pad v0.1.4
Build failed, waiting for other jobs to finish...
/Users/david/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.30/src/lib.rs:370:34: 370:48 error: unstable feature
/Users/david/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.30/src/lib.rs:370 #![cfg_attr(feature = "pattern", feature(core))]
                                                                                                                          ^~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Could not compile `users`.

To learn more, run the command again with --verbose.
make: *** [target/release/exa] Error 101
```

**Comment by mingchen** [comment]
another failed on Mac OS X 10.10.3.
$ rustc --version
rustc 1.1.0-nightly (c4b23aec4 2015-04-29) (built 2015-04-28)

   Compiling git2 v0.2.9 (https://github.com/alexcrichton/git2-rs.git#42776b31)
   Compiling exa v0.2.0 (file:///Users/ming/Downloads/opensources/exa)
src/main.rs:16:1: 16:22 error: can't find crate for `unicode`
src/main.rs:16 extern crate unicode;
               ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `exa`.

To learn more, run the command again with --verbose.
make: *** [target/release/exa] Error 101

**Comment by ogham** [comment]
I finally merged the new_fs branch (in commit ffcc6fa1793b9f92fda0f001de81230900560fac), so everything should be back to normal now. Sorry for the inconvenience!

The reason it took so long was that we were reliant on certain Unix-specific extensions, which were only implemented by the Rust devs a few days ago. So your choices were having a version that doesn't compile, or a version that *does* compile but displays the wrong information. I chose the former, but with the new functionality, it's all working again.
